server:
  port: 8081

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mysql://localhost:3306/logistics_user_db
    username: root
    password: Kavi2505@@@@

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

jwt:
  secret: abcdefghijklmnopqrstuvwxyz1234567890ABCDEFGHIJKLMNOPQRSTUVWXYZ